from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

class TestEstudiantes:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.driver.get('http://localhost:5173/students')
        time.sleep(2)
    def teardown_method(self):
        self.driver.quit()
        print("Prueba terminada")

    def test_estudiantes(self):
        # Registrar Nuevo Estudiante
        self.driver.find_element(By.XPATH,"//div[@class = 'flex justify-between items-center mb-4']//button[contains(@class, 'inline-flex items-center justify-center')]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@name = 'name']").send_keys('Juan José')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'last_name']").send_keys('Pérez')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'second_last_name']").send_keys('Sanchez')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'ci']").send_keys('13877820')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@placeholder = 'Ingresar fecha']").send_keys('06/05/2004')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//div[text() = '6']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']//option[@value = 'LA PAZ']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'phone']").send_keys('68862427')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']//option[@value = 'MASCULINO']").click()
        time.sleep(1)
        upload_button = self.driver.find_element(By.XPATH, "//input[@id = 'image-upload']")
        image_path = r""
        upload_button.send_keys(image_path)
        time.sleep(2)
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[contains(@class, 'text-white bg-gradient-to-r from-green-400')]").click()
        time.sleep(9)

        # Buscar y Ver Perfil del Estudiante
        self.driver.find_element(By.XPATH,"//input[@type = 'search']").send_keys('13877820')
        time.sleep(10)
        self.driver.find_element(By.XPATH,"//div[contains(@class, 'relative w-11 h-6 bg-gray-200 peer-focus:outline-none')]").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[text() = 'Confirmar']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//div[contains(@class, 'relative w-11 h-6 bg-gray-200 peer-focus:outline-none')]").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[text() = 'Confirmar']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[text() = 'Ver Perfil']").click()
        time.sleep(10)
        self.driver.find_element(By.XPATH,"//button[text() = 'Volver']").click()
        time.sleep(7)

        # Editar al Estudiante
        self.driver.find_element(By.XPATH,"//input[@type = 'search']").send_keys('13877820')
        time.sleep(10)
        self.driver.find_element(By.XPATH,"//button[text() = 'Editar']").click()
        time.sleep(5)
        self.driver.find_element(By.XPATH,"//input[@name = 'name']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'name']").send_keys('Miguel Fernando')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'last_name']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'last_name']").send_keys('Apaza')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'second_last_name']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'second_last_name']").send_keys('Figueroa')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'ci']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'ci']").send_keys('2033166')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@placeholder = 'Ingresar fecha']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//select[@class = 'react-datepicker__year-select']//option[@value = '2000']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//div[text() = '6']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']//option[@value = 'COCHABAMBA']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'phone']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'phone']").send_keys('73044815')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']//option[@value = 'MASCULINO']").click()
        time.sleep(1)
        upload_button = self.driver.find_element(By.XPATH, "//input[@type = 'file']")
        image_path = r""
        upload_button.send_keys(image_path)
        time.sleep(2)
        self.driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[contains(@class, 'text-white bg-gradient-to-r from-green-400')]").click()
        time.sleep(9)

        # Eliminar al Estudiante
        self.driver.find_element(By.XPATH,"//input[@type = 'search']").send_keys('2033166')
        time.sleep(10)
        self.driver.find_element(By.XPATH,"//button[text() = 'Eliminar']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[text() = 'Confirmar']").click()
        time.sleep(5)