""" Incluir acá los test cases para el módulo específico. """
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from webdriver_manager.chrome import ChromeDriverManager
import time

class TestDocentes:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.driver.maximize_window()
        self.driver.get('http://localhost:5173/teachers')
        time.sleep(2)
    def teardown_method(self):
        self.driver.quit()
        print("Prueba terminada")

    def test_docentes(self):
        # Registrar Nuevo Docente
        self.driver.find_element(By.XPATH,"//button[contains(@class, 'inline-flex items-center justify-center text-sm px-5 py-2.5 mb-4 font-medium')]").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//input[@name = 'name']").send_keys('Sergio')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'last_name']").send_keys('Paz')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'second_last_name']").send_keys('Chavez')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'ci']").send_keys('6894308')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'phone']").send_keys('68062423')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']//option[@value = 'LA PAZ']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@placeholder = 'Ingresar fecha']").send_keys('06/03/2002')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//div[text() = '6']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'specialty']").send_keys('Contador')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']//option[@value = 'MASCULINO']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//button[contains(@class, 'text-white bg-gradient-to-r from-green-400')]").click()
        time.sleep(9)

        # Editar al Docente
        self.driver.find_element(By.XPATH,"//input[@type = 'search']").send_keys('6894308')
        time.sleep(8)
        self.driver.find_element(By.XPATH,"//button[text() = 'Editar']").click()
        time.sleep(7)
        self.driver.find_element(By.XPATH,"//input[@name = 'name']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'name']").send_keys('Miguel Perez')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'last_name']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'last_name']").send_keys('Apaza')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'second_last_name']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'second_last_name']").send_keys('Figueroa')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'ci']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'ci']").send_keys('2033166')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@placeholder = 'Ingresar fecha']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//select[@class = 'react-datepicker__year-select']//option[@value = '2000']").click()
        time.sleep(2)
        self.driver.find_element(By.XPATH,"//div[text() = '6']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'placeofbirth']//option[@value = 'COCHABAMBA']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'phone']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'phone']").send_keys('73044815')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//select[@name = 'gender']//option[@value = 'MASCULINO']").click()
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//input[@name = 'specialty']").clear()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//input[@name = 'specialty']").send_keys('Diseñador')
        time.sleep(1)
        self.driver.find_element(By.XPATH,"//button[text() = 'Actualizar']").click()
        time.sleep(7)

        # Eliminar al Docente
        self.driver.find_element(By.XPATH,"//input[@type = 'search']").send_keys('2033166')
        time.sleep(8)
        self.driver.find_element(By.XPATH,"//button[text() = 'Eliminar']").click()
        time.sleep(3)
        self.driver.find_element(By.XPATH,"//button[text() = 'Confirmar']").click()
        time.sleep(6)